name: Test

on:
  pull_request:
    branches:
      - cl
  push:
    branches:
      - cl
    tags:

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.nsq-version }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - Ubuntu
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        nsq-version:
          - "https://github.com/cloudlinux/nsq/releases/download/1.2.1-1/nsq-1.2.1-1.linux-amd64.go1.19.1.tar.gz"
    env:
      PY_COLORS: 1
      PYTEST_ADDOPTS: --cov-report=xml
    steps:
      - uses: actions/checkout@master
      - name: Download NSQ
        run: |
          curl -sSL "${{matrix.nsq-version}}" | tar -xzv --strip-components=1
          sudo ln -s ./bin/nsqd /bin/nsqd
          ./bin/nsqd --version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: python -m pip install tox-gh-actions
      - name: Prepare test environment
        run: tox --notest
      - name: Test
        run: |
          export PATH=bin:$PATH
          tox
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          name: ${{ runner.os }}-${{ matrix.python-version }}
